config/routes.rb
Rails.application.routes.draw do
  resources :contents
  root "statics#index"
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  # Admin routes
  namespace :admin do
    resources :tests
    resources :contents
    resource :dashboard, only: [:show]

    resources :lessons do
      resources :contents
    end
    
    get 'dashboards', to: 'dashboards#index', as: 'dashboards'
   
    resources :contents
  end
  resources :statics
  resources :answers
  resources :questions
  devise_for :users
  

   # Client routes
   namespace :client do
    resources :tests
    resources :contents
    resource :dashboard, only: [:show]

    resources :lessons do
      resources :contents
    end
     get 'dashboards', to: 'dashboards#index', as: 'dashboards'
  

    
     resources :lessons, only: [:index, :show]
  end
  
   
   # Add other client routes here
  

  

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/content.rb
class Content < ApplicationRecord
    belongs_to :lesson
    has_rich_text :body
    has_one_attached :image
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]
  before_action :set_lesson, only: %i[ new create]


  def index
    @contents = Content.all
  end

  def show
    @content = Content.find(params[:id])
  end

  def edit
    
  end
  
  # GET /contents/new
  def new
    @content = @lesson.contents.build
    @all_contents = Content.all
  end

  # POST /contents or /contents.json
  def create
    @content = @lesson.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to admin_lesson_path(@content.lesson), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to admin_contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to admin_content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def content_params
    params.require(:content).permit(:title, :content)
  end
end

app/controllers/client/answers_controller.rb
class Client::AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to answer_url(@answer), notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answer_url(@answer), notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy!

    respond_to do |format|
      format.html { redirect_to answers_url, notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.fetch(:answer, {})
    end
end

app/controllers/client/contents_controller.rb
class Client::ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy!

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:title, :content)
    end
end

app/controllers/client/dashboards_controller.rb
class Client::DashboardsController < ApplicationController
  before_action :set_dashboard, only: %i[ show edit update destroy ]

  # GET /dashboards or /dashboards.json
  def index
    
  end

  # GET /dashboards/1 or /dashboards/1.json
  def show
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards or /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to dashboard_url(@dashboard), notice: "Dashboard was successfully created." }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1 or /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to dashboard_url(@dashboard), notice: "Dashboard was successfully updated." }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1 or /dashboards/1.json
  def destroy
    @dashboard.destroy!

    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: "Dashboard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dashboard_params
      params.fetch(:dashboard, {})
    end
end

app/controllers/client/lessons_controller.rb
class Client::LessonsController < ApplicationController
  # Other actions ...

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  def show
      @lesson = Lesson.find(params[:id])
      @contents = @lesson.contents
  end
  

    # GET /lessons
    def index
      @lessons = Lesson.all
    end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to admin_dashboard_path, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.require(:lesson).permit(:title, :content)
  end
  
end

app/controllers/client/questions_controller.rb
class Client::QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy!

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.fetch(:question, {})
    end
end

app/controllers/client/tests_controller.rb
class Client::TestsController < ApplicationController
  before_action :set_test, only: %i[ show edit update destroy ]

  # GET /tests or /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1 or /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests or /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to test_url(@test), notice: "Test was successfully created." }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1 or /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to test_url(@test), notice: "Test was successfully updated." }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1 or /tests/1.json
  def destroy
    @test.destroy!

    respond_to do |format|
      format.html { redirect_to tests_url, notice: "Test was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def test_params
      params.fetch(:test, {})
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/client/contents/_content.html.erb
<div id="<%= dom_id content %>">
</div>

app/views/client/contents/_form.html.erb
<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/client/contents/edit.html.erb
<h1>Editing content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Show this content", @content %> |
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/client/contents/index.html.erb
<div class="flex">
  <div class="w-full p-6">
    <div class="flex justify-between items-center mb-4">
      <h1 class="text-xl font-bold">Content</h1>
      <%= link_to "Tambah", new_admin_content_path, class: "bg-blue-900 text-white py-2 px-4 rounded hover:bg-blue-700" %>
    </div>

    <div class="grid grid-cols-3 gap-4">
      <% @contents.each do |content| %>
        <div class="border p-4 shadow hover:shadow-md transition-shadow duration-300">
          <h2 class="font-bold text-indigo-700"><%= content.title %></h2>
          <p class="text-gray-500">Your text here.</p>
          <%= link_to "View Content", content_path(content), class: "text-blue-500 hover:underline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/client/contents/new.html.erb
<h1 class="t3text-lg font-bold text-gray-900 mb-2 ml-60 text-center">Tambah Lesson Baru</h1>

<div class="flex justify-center items-center min-h-screen ml-60">
  <div class="w-full max-w-4xl bg-white p-8 rounded shadow-md border border-gray-300">
    <%= form_with(model: @content, url: admin_contents_path, local: true) do |form| %>


      <div class="field mb-4">
        <%= form.text_field :title, placeholder: "Title", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="field mb-4">
        <%= form.rich_text_area :content, placeholder: "I am your rich text editor.", rows: 10, class: "w-full border rounded p-3 text-gray-700 focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="flex justify-end space-x-2">
        <%= form.submit "Save", class: "bg-indigo-800 text-white font-semibold py-2 px-4 rounded-lg mr-4" %>
        <%= link_to 'Batal', admin_lessons_path, class: "bg-indigo-800 text-white font-semibold py-2 px-4 rounded-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/client/contents/show.html.erb
<div class="flex justify-center">
  <div class="w-full max-w-4xl px-4 sm:px-6 lg:px-8 flex flex-col ml-60">
    
    <!-- Title Section -->
    <div class="text-center mb-6">
      <h1 class="text-3xl font-extrabold text-gray-900">Lesson</h1>
      <h2 class="text-xl font-semibold text-gray-700 mt-2"><%= @content.lesson.title %></h2>
    </div>

    <!-- Content Section -->
    <div class="bg-gray-100 p-6 rounded-lg shadow-inner mb-6 flex-grow">
      <h3 class="text-lg font-semibold text-gray-600 mb-3 ml-60"><%= @content.title %></h3>
      <div class="text-gray-800 leading-relaxed">
        <%= @content.content.html_safe %>
      </div>
    </div>

    <!-- Action Buttons at the Bottom -->
    <div class="flex justify-center space-x-4 mt-6">
      <%= link_to "Back", client_lessons_path, class: "bg-gray-300 text-gray-700 py-2 px-6 rounded hover:bg-gray-400 transition ease-in-out duration-150" %>
    </div>

  </div>
</div>