config/routes.rb
Rails.application.routes.draw do
  resources :contents
  root "statics#index"
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  # Admin routes
  namespace :admin do
    resources :tests
    resources :contents
    resource :dashboard, only: [:show]

    resources :lessons do
      resources :contents
    end
    
    get 'dashboards', to: 'dashboards#index', as: 'dashboards'
   
    resources :contents
  end
  resources :statics
  resources :answers
  resources :questions
  devise_for :users
  

   # Client routes
   namespace :client do
    resources :tests
    resources :contents
    resource :dashboard, only: [:show]

    resources :lessons do
      resources :contents
    end
     get 'dashboards', to: 'dashboards#index', as: 'dashboards'
  

    
     resources :lessons, only: [:index, :show]
  end
  
   
   # Add other client routes here
  

  

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    has_many :contents, dependent: :destroy
    belongs_to :user
    has_rich_text :content
    has_one_attached :file
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
  before_action :authenticate_user!
  # Other actions ...

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  def show
    @lesson = Lesson.find(params[:id])
    @contents = @lesson.contents
  end

  #GET /lesson/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  def content
    @lesson = Lesson.find(params[:id])
    # Add any additional logic needed for displaying the content
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to admin_lessons_path, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

    # GET /lessons
    def index
      @lessons = Lesson.all
    end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.user_id = current_user.id

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to admin_lessons_path, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @lesson = Lesson.find(params[:id])
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to admin_lesson_path(@lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.require(:lesson).permit(:title, :context)
  end
  
end

app/controllers/client/answers_controller.rb
class Client::AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to answer_url(@answer), notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answer_url(@answer), notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy!

    respond_to do |format|
      format.html { redirect_to answers_url, notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.fetch(:answer, {})
    end
end

app/controllers/client/contents_controller.rb
class Client::ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy!

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:title, :content)
    end
end

app/controllers/client/dashboards_controller.rb
class Client::DashboardsController < ApplicationController
  before_action :set_dashboard, only: %i[ show edit update destroy ]

  # GET /dashboards or /dashboards.json
  def index
    
  end

  # GET /dashboards/1 or /dashboards/1.json
  def show
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards or /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to dashboard_url(@dashboard), notice: "Dashboard was successfully created." }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1 or /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to dashboard_url(@dashboard), notice: "Dashboard was successfully updated." }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1 or /dashboards/1.json
  def destroy
    @dashboard.destroy!

    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: "Dashboard was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dashboard_params
      params.fetch(:dashboard, {})
    end
end

app/controllers/client/lessons_controller.rb
class Client::LessonsController < ApplicationController
  # Other actions ...

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  def show
      @lesson = Lesson.find(params[:id])
      @contents = @lesson.contents
  end
  

    # GET /lessons
    def index
      @lessons = Lesson.all
    end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to admin_dashboard_path, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.require(:lesson).permit(:title, :content)
  end
  
end

app/controllers/client/questions_controller.rb
class Client::QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy!

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.fetch(:question, {})
    end
end

app/controllers/client/tests_controller.rb
class Client::TestsController < ApplicationController
  before_action :set_test, only: %i[ show edit update destroy ]

  # GET /tests or /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1 or /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests or /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to test_url(@test), notice: "Test was successfully created." }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1 or /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to test_url(@test), notice: "Test was successfully updated." }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1 or /tests/1.json
  def destroy
    @test.destroy!

    respond_to do |format|
      format.html { redirect_to tests_url, notice: "Test was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def test_params
      params.fetch(:test, {})
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/client/lessons/_form.html.erb
<%= form_with(model: @lesson, local: true) do |form| %>
  <% if @lesson.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>
      <ul>
        <% @lesson.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Title Field -->
  <div class="mb-4">
    <%= form.text_field :title, placeholder: "Title", class: "w-full border-2 border-purple-600 p-2 rounded-md" %>
  </div>

  <!-- Rich Text Editor -->
  <div class="mb-4">
    <%= form.label :content, "Content", class: "sr-only" %>
    <%= form.rich_text_area :content, class: "w-full border-2 border-purple-600 p-2 rounded-md h-40" %>
  </div>

  <!-- Save and Cancel Buttons -->
  <div class="flex justify-end space-x-2">
    <%= form.submit "Save", class: "bg-purple-600 text-white px-4 py-2 rounded-md" %>
    <%= link_to "Cancel", lessons_path, class: "bg-purple-600 text-white px-4 py-2 rounded-md" %>
  </div>
  
<% end %>

app/views/client/lessons/_index.html.erb
sd

app/views/client/lessons/_lesson.html.erb
<div class="w-3/4 mx-auto p-8 mt-10 flex flex-col space-y-6 ml-60">
<!-- Title -->
<h1 class="text-2xl font-bold text-gray-900 ml-60">Pengenalan Cara Set-Up</h1>

  <!-- Right side (Full-height container) -->
  <div id="<%= dom_id(@lesson) %>" class="w-full border-4 border-gray-200 p-6 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300 bg-white">

    <!-- Lesson Context -->
    <p class="text-gray-700 text-lg leading-relaxed"><%= @lesson.context %></p>

    <!-- Contents Grid -->
    <div class="mt-6 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      <% @contents.each do |content| %>
        <div class="border border-gray-300 rounded-lg p-4 shadow-md hover:shadow-lg transition-shadow duration-300 bg-gray-50">
          <h3 class="text-lg font-semibold text-gray-900 mb-2 "><%= content.title %></h3>
          <p class="text-sm text-gray-700"><%= truncate(content.content, length: 30) %></p>
          <%= link_to "View Content", client_content_path(content), class: "text-blue-500 hover:underline" %>
          </div>
      <% end %>
    </div>

    <!-- Bottom Left Actions -->
    <div class="flex justify-end mt-6">
    <%= link_to "Back to lessons", client_lessons_path, class: "text-blue-600 hover:underline transition duration-200" %>
    </div>
  </div>
</div>

app/views/client/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Show this lesson", @lesson %> |
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/client/lessons/index.html.erb
<div class="flex justify-center">
  <div class="w-full max-w-6xl p-6">

    <div class="flex justify-between items-center mb-2 ml-10">
      <h1 class="text-2xl font-bold text-gray-800 ml-60">Lesson</h1>
       </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 ml-60">
      <% @lessons.each do |lesson| %>
        <div class="border border-gray-200 p-4 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
          <h2 class="font-bold text-indigo-700 text-lg mb-2"><%= lesson.title %></h2>
          <%= link_to "View Lesson", client_lesson_path(lesson), class: "text-blue-500 hover:underline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/client/lessons/new.html.erb
<h1 class="t3text-lg font-bold text-gray-900 mb-2 ml-60 text-center">Tambah Lesson Baru</h1>

<div class="flex justify-center items-center min-h-screen ml-60">
  <div class="w-full max-w-4xl bg-white p-8 rounded shadow-md border border-gray-300">
    <%= form_with(model: @lesson, url: admin_lessons_path, local: true) do |form| %>
      <% if @lesson.errors.any? %>
        <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
          <h2 class="text-xl font-semibold mb-2"><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>
          <ul class="list-disc list-inside">
            <% @lesson.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field mb-4">
        <%= form.text_field :title, placeholder: "Title", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="field mb-4">
        <%= form.rich_text_area :content, placeholder: "I am your rich text editor.", rows: 10, class: "w-full border rounded p-3 text-gray-700 focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="field mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2">File</label>
      <%= form.file_field :file, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    

      <div class="flex justify-end">
        <%= form.submit "Save", class: "bg-indigo-800 text-white font-semibold py-2 px-4 rounded-lg mr-4" %>
        <%= link_to 'Batal', admin_lessons_path, class: "bg-indigo-800 text-white font-semibold py-2 px-4 rounded-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/client/lessons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lesson %>

<div>
 <%= link_to "Back to lessons", client_lessons_path %>

</div>